import { Geist } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import localFont from 'next/font/local'
import Footer from '@/components/Footer'
import Providers from './providers'
// import localFont from '../../public/fonts/satoshi/Satoshi-Regular.otf'

const Satoshi = localFont({
  src: '../../public/fonts/satoshi/Satoshi-Regular.otf',
  variable: '--font-custom',
})

export const IntegralCF = localFont({
  src: '../../public/fonts/IntegralCF/IntegralCF-Bold.otf',
  variable: '--font-custom',
})

const geist = Geist({
  subsets: ['latin'],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${Satoshi.className} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <Providers>
          <Navbar />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
