# Generated by Django 5.2.8 on 2026-08-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_productimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(upload_to="products/"),
        ),
    ]
