# Generated by Django 5.2.8 on 2026-08-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="color",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="size",
            field=models.CharField(blank=True, null=True),
        ),
    ]
