# Generated by Django 5.2.8 on 2026-08-12 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
        ("products", "0003_alter_productimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock",
                to="products.product",
            ),
        ),
    ]
